import { useState } from "react";
import { useNavigate } from "react-router";
import api from "../services/api";

const categories = ["Road & Infrastructure", "Waste Management", "Water Supply", "Electricity", "Public Safety", "Sanitation", "Other"];
const ReportIssue = () => {
  const navigate = useNavigate();
  const [form, setForm] = useState({ title: "", category: categories[0], description: "", ward: "", latitude: "", longitude: "" });
  const [files, setFiles] = useState([]); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const update = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }));
  const useLocation = () => navigator.geolocation?.getCurrentPosition(({ coords }) => setForm((current) => ({ ...current, latitude: coords.latitude.toFixed(6), longitude: coords.longitude.toFixed(6) })), () => setError("Location was unavailable. Enter the coordinates manually."));
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const data = new FormData(); Object.entries(form).forEach(([key, value]) => data.append(key, value)); files.forEach((file) => data.append("attachments", file)); const response = await api.post("/complaints", data); navigate(`/complaints/${response.data.data._id}`); } catch (requestError) { setError(requestError.response?.data?.message || "Could not submit your report."); } finally { setSaving(false); } };
  return <main className="site-shell report-page"><section className="report-intro"><p className="eyebrow">New community report</p><h1>Tell us what needs attention.</h1><p>Your report is public. It will be routed to the relevant city team and the community can follow progress.</p></section><form className="report-form" onSubmit={submit}>{error && <div className="notice notice--error">{error}</div>}<label>What is the issue?<input name="title" value={form.title} onChange={update} placeholder="e.g. Deep pothole near the school gate" required maxLength="140" /></label><label>Category<select name="category" value={form.category} onChange={update}>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label className="form-wide">Describe the problem<textarea name="description" value={form.description} onChange={update} rows="6" placeholder="Include details that will help the department understand and resolve the issue." required /></label><label>Ward or area<input name="ward" value={form.ward} onChange={update} placeholder="e.g. Ward 12, Dhanmondi" /></label><label>Photo evidence<input type="file" accept="image/*" multiple onChange={(event) => setFiles(Array.from(event.target.files || []))} /></label><div className="location-fields form-wide"><div><label>Latitude<input type="number" step="any" name="latitude" value={form.latitude} onChange={update} required /></label><label>Longitude<input type="number" step="any" name="longitude" value={form.longitude} onChange={update} required /></label></div><button className="text-button" type="button" onClick={useLocation}>Use my current location</button></div><button className="button button--primary form-submit" disabled={saving}>{saving ? "Submitting report…" : "Submit community report"}</button></form></main>;
};
export default ReportIssue;
